version: '3.7'
services: 
    frontend:
        build: 
            context: ./client
        command: yarn start
        volumes: 
            - ./client/src:/usr/app/src
        depends_on: 
            - backend
        environment: 
            - CHOKIDAR_USEPOLLING=true
        tty: true 
        stdin_open: true
    backend:
        build: 
            context: ./server
        command: yarn run dev
        volumes: 
            - ./server/src:/usr/app/src
        environment: 
            - MONGO_URI=mongodb://mongoServer:27017/video-chat
            - CHOKIDAR_USEPOLLING=true
        stdin_open: true
        tty: true
        depends_on: 
            - mongoServer
    mongoServer:
        image: mongo:latest
        ports: 
            - 27017:27017
        logging:
            driver: "none"
        volumes: 
            - mongodb_data_container:/data/db
    nginx:
        build: 
            context: ./nginx
        volumes: 
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
        ports: 
            - 8080:80
        depends_on: 
            - backend
            - frontend
volumes: 
    mongodb_data_container:
        

    # client:
    #     build: 
    #         context: ./client
    #     command: yarn start
    #     volumes: 
    #         - ./client/src:/usr/app/src
    #     ports: 
    #         - 3000: 3000
    #     depends_on:
    #         - server
    #     environment: 
    #         - CHOKIDAR_USEPOLLING=true
    #     tty: true
    #     stdin_open: true
    # server:
    #     build: 
    #     context: ./server
    #     command: yarn run dev
    #     volumes: 
    #         - .backend/src:/usr/app/server
    #     depends_on: mongoServer
    # mongoServer:
    #     image: mongo
    #     restart: always
    #     volumes: 
    #         - mongodb_api:/data/db
    #     environment:
    #     MONGO_INITDB_ROOT_USERNAME: root
    #     MONGO_INITDB_ROOT_PASSWORD: example
    #     ports: 
    #     - 2701: 2701
    # nginx:
    #     build: 
    #     context: ./nginx
    #     volumes: 
    #         - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    #     image: nginx:1.19.6
    #     volumes: ./nginx/nginx.conf:/usr/app
    #     ports: 
    #         - 8080:80
    #     depends_on: 
    #         - client
    #         - server


